name: Bundle and release with docs

on:
  push:
    tags:
      - "*"

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    name: Build dist files
    runs-on: ubuntu-latest
    steps:
      - name: Parse version from tag refs
        shell: bash
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
        id: version_to_publish
      - name: Check current published version
        shell: bash
        run: echo ::set-output name=version::$(npm view faunadb version)
        id: current_version
      - run: echo ${{steps.current_version.outputs.version}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: "10.18.0"
      - name: Install dependencies
        run: npm ci
      - name: Create dist folder
        run: mkdir dist
      - name: Run browserify
        run: npm run browserify
      - name: Run browserify-min
        run: npm run browserify-min
      - name: Publish to npm
        run: npm publish --tag ${{steps.version_to_publish.outputs.version}} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
  # publish_docs:
  #   name: Publish documentation
  #   needs: [build, publish]
  #   runs-on: ubuntu-latest
