name: Bundle and release with docs

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    name: Build dist files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: "10.18.0"
      - name: Install dependencies
        run: npm ci
      - name: Create dist folder
        run: mkdir dist
      - name: Run browserify
        run: npm run browserify
      - name: Run browserify-min
        run: npm run browserify-min
      - name: Publish to npm
        run: npm publish --tag ${{github.ref}} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
  # publish:
  #   name: Publish to npm registry
  #   needs: build
  #   runs-on: ubuntu-latest
  # publish_docs:
  #   name: Publish documentation
  #   needs: [build, publish]
  #   runs-on: ubuntu-latest
